version: '3.8'
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: autocado
      POSTGRES_PASSWORD: autocado1
      POSTGRES_DB: autocado
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  backend:
    build: ./backend
    environment:
      PORT: 3000
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: autocado
      DB_PASSWORD: autocado1
      DB_NAME: autocado
      JWT_SECRET: supersecret
    depends_on:
      - db
    ports:
      - '3000:3000'
  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: http://localhost:3000
    depends_on:
      - backend
    ports:
      - '3200:80'
volumes:
  db_data:
